### ISSUE TITLE
[Bug]: No directive `automodule` from `sphinx-apidoc`

### ISSUE THREAD

**Issue by jamesbraza** [rstcheck/rstcheck-core#62]
### To Dos

- [X] I tested with the [latest released version](https://github.com/rstcheck/rstcheck/releases/latest).
- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.
- [X] I added a very descriptive title to this issue.

### Example Code (rst)

```rst
scripts package
===============

Submodules
----------

scripts.foo module
-------------------

.. automodule:: scripts.foo
   :members:
   :undoc-members:
   :show-inheritance:
```

### Relevant log output

```Shell
scripts.rst:10: (INFO/1) No directive entry for "automodule" in module "docutils.parsers.rst.languages.en".
scripts.rst:10: (ERROR/3) Unknown directive type "automodule".
```

### Description

`sphinx-apidoc` fields don't appear to be recognized, how can this be solved?

### Operating System

macOS

### Python Version

3.11.4

### rstcheck Version

These come from `pip install rstcheck[sphinx]`
- rstcheck CLI Version: 6.1.2
- rstcheck-core Version: 1.0.3

**Comment by Cielquan** [comment]
Currently rstcheck only supports standard rst and default sphinx directives. Therefore you would need to put `automodule` on the ignorelist for directives.

Example `.rstcheck.cfg` file:
```ini
[rstcheck]
ignore_directives = automodule
```

There is currently a feature request which aims to change this: https://github.com/rstcheck/rstcheck-core/issues/68
