### ISSUE TITLE
[Feature]: support yaml code block checks

### ISSUE THREAD

**Issue by pshchelo** [rstcheck/rstcheck-core#77]
### To Dos

- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

Yaml is so pervasive nowadays..

Minimal YAML support in rstcheck would be nice, e.g. the same way as for JSON - just try to `yaml.load` it and report on errors if any.

Can be done as optional dependency on PyYaml, and running the check only if that is installed, otherwise skipping.

### Operating System

Linux

### Python Version

3.10

### rstcheck Version

master

**Comment by Cielquan** [comment]
Released in 1.2.0
